import type { Copy } from "./index";

export const en: Copy = {
  meta: {
    title: "Stello — if it misses, you win",
    description:
      "Join with a bank transfer. If the goal is missed, your money and your share of the bonus come back on their own.",
  },

  format: {
    locale: "en-US",
    over: "time is up",
    day: "d",
    hour: "h",
    minute: "m",
    second: "s",
  },

  verdict: { succeeded: "Made it", failed: "Missed", waiting: "Waiting", open: "Open" },

  steps: {
    account: "Opening your account",
    trustline: "Allowing your account to receive money",
    signin: "Signing in to the payment institution",
    customer: "Filing your details",
    ticket: "Getting your reference code",
    deposit: "Preparing the IBAN",
    "waiting-transfer": "Waiting for your transfer",
    "waiting-chain": "Writing your pledge to the chain",
    settled: "Settling the campaign",
    claimed: "Moving your money to your account",
    withdrawing: "Sending it to your IBAN in lira",
    "paid-out": "Done",
  },

  nav: {
    proof: "Proof",
    how: "How it works",
    guarantees: "Guarantees",
    privacy: "No crypto",
    toLight: "Switch to the light theme",
    toDark: "Switch to the dark theme",
    light: "Light",
    dark: "Dark",
    campaigns: "Campaigns",
    langLabel: "Türkçe'ye geç",
  },

  hero: {
    headline: "If the goal is missed, you are the one who wins.",
    mark: "you are the one",
    lede: "Send lira from your banking app and join — no wallet, no crypto. If it works out, the thing happens; if it does not, your money and your share of the bonus the organizer locked up front come back on their own.",
    join: "Join a campaign",
    joinHint: "a bank transfer is enough",
    create: "Start a campaign",
    createHint: "you lock the bonus",
    back: "Back to your campaigns",
    backHint: "this browser remembers you",
    countCampaigns: "campaigns started",
    countPledged: "USDC pledged",
    countPeople: "people joined",
    award: "Stellar testnet · live from the chain",
  },

  proof: {
    title: "The goal was missed. The money came back on its own.",
    lede: "Not a promise — a record. The run below really happened on the test network, and anyone can check every step of it on chain.",
    pledgedLabel: "Pledged",
    pledgedOf: "/ 100 goal",
    pledgedNote: "deadline passed, goal missed",
    lateLabel: "A transfer that arrived after the deadline",
    lateValue: "Refunded",
    latePill: "3 units · returned in the same transaction",
    returnedLabel: "Returned to the backer",
    returnedValue: "5 / 5 — all of it",
    returnedNote: "without needing their signature",
    jailTitle: "The backer did nothing. The money came back anyway.",
    jailLede: "Not a hypothetical — it ran on the test network, in a real campaign. Step by step:",
    jailSteps: [
      "The deadline passed and the goal was missed. The backer *never even opened the app.*",
      "A completely different account triggered the refund — the contract does not care who calls it.",
      "The money went to the backer's own account, not the caller's. **Down to the last cent.**",
    ],
    jailFoot: "One transaction, a few seconds — September 2026, Stellar testnet.",
    linkRefund: "See the refund on the explorer ↗",
    linkRouter: "The router contract ↗",
  },

  how: {
    title: "How it works",
    lede: "The only thing you do is send a transfer. The contract follows the rest.",
    steps: [
      {
        n: "01",
        t: "Send your transfer",
        d: "To the campaign's IBAN, with the reference code that belongs to you. No wallet to install, no phrase to keep safe, no crypto to buy first.",
      },
      {
        n: "02",
        t: "Take your place on chain",
        d: "The moment the money lands, your pledge is written to the contract. The counter moves in front of everyone; nobody keeps the list by hand.",
      },
      {
        n: "03",
        t: "Either it happens, or you win",
        d: "If the goal is met, the thing happens. If it is not, your money and your share of the bonus come back to you — without you doing a thing.",
      },
    ],
    link: "How it was built →",
  },

  guarantees: {
    title: "Four things the contract enforces",
    lede: "Not settings in an app, and certainly not somebody saying “don't worry”. Rules the contract checks before any money moves.",
    items: [
      {
        n: "01",
        t: "The bonus is locked up front",
        d: "A campaign does not open for pledges until the organizer has put the bonus into the contract. The promise sits there as money, not as words.",
      },
      {
        n: "02",
        t: "A cap per person",
        d: "A bonus share counts up to a cap per person. Dropping a large amount in at the last minute will not sweep the bonus.",
      },
      {
        n: "03",
        t: "Refunds need no signature",
        d: "Anyone can trigger the money going back, but it only ever goes to the person it belongs to. Lose your phone and you still get paid.",
      },
      {
        n: "04",
        t: "One transfer counts once",
        d: "Every payment has a single identity on chain. Even if the relay runs twice, the contract refuses the second one.",
      },
    ],
    keyText:
      "In “if enough people join” situations, everyone waits for somebody else to go first. ",
    keyStrong: "Here waiting earns you nothing and joining does.",
    link: "The contract mechanics →",
  },

  privacy: {
    title: "Take the chain's guarantee — without learning the chain.",
    lede: "To join, you do the one thing you already know how to do: send a transfer. No wallet to set up, no phrase to keep, no exchange to buy from. And still, the rule your money follows is not a company's word but a contract anyone can read.",
    cards: [
      { k: "Wallet", v: "•••••", note: "not needed" },
      { k: "Buying crypto", v: "•••••", note: "not needed" },
      { k: "Your pledge", v: "Recorded", note: "on chain, in the open" },
    ],
    link: "How a bank transfer becomes a contract call →",
  },

  finalCta: {
    title: "You are one transfer away.",
    lede: "No wallet to install, no phrase to keep safe, no crypto to buy first. Pick a campaign, send to the IBAN; the contract follows the rest.",
    browse: "Browse campaigns",
    create: "Start a campaign →",
  },

  footer: {
    line: "A bank transfer becomes a contract call — your rules sit in the contract, not in a promise.",
    product: "Product",
    campaigns: "Campaigns",
    create: "Start a campaign",
    resources: "Resources",
    architecture: "Architecture and trust model ↗",
    onChain: "On chain",
    router: "Router contract",
    campaignContract: "Campaign contract",
    landing: "Landing account",
    badge: "Stellar Testnet",
    openSource: "Open source, readable line by line.",
    totals: "%c campaigns · %a USDC pledged — all of it checkable above.",
    author: "Made by Seyit Ali Değirmen",
    event: "Stellar Pro Hackathon · Istanbul, September 2026",
  },

  shell: {
    campaigns: "Campaigns",
    create: "Start a campaign",
    testnet: "⚠ Test network — test money, not real money.",
    docs: "How it works ↗",
    close: "Close",
  },

  campaignsPage: {
    emptyTitle: "For the things that happen if enough people show up.",
    emptyNote:
      "Set the goal and the deadline, then lock the bonus. Backers only send a transfer; if the goal is missed, their money and their bonus shares come back on their own.",
    emptyCta: "Start the first campaign",
    featuredEyebrow: "Open to you right now",
    featuredLeft: "%t left",
    peopleJoined: "people joined",
    openCampaign: "Open the campaign →",
    reading: "Reading…",
    noneYet: "None right now",
    noneNote:
      "An open campaign appears here when there is one — with its time left, what it has raised, and how many people joined.",
    allCampaigns: "All campaigns",
    open: "open",
    closed: "closed",
    colLeft: "Left",
    colStatus: "Status",
    colCampaign: "Campaign",
    colRaised: "Raised",
    readingChain: "Reading from the chain…",
    noCampaigns: "No campaigns yet.",
    howToJoin: "How to join",
    joinSteps: [
      "Pick a campaign and enter how much lira you will send.",
      "Send a transfer to the IBAN shown, with the reference code that belongs to you.",
      "If the goal is missed, your money and your bonus share come back on their own.",
    ],
    rules: "Rules",
    ruleBonus: "Bonus",
    ruleBonusValue: "locked up front",
    ruleRefund: "Refunds",
    ruleRefundValue: "need no signature",
    ruleOnce: "One transfer",
    ruleOnceValue: "counts once",
    create: "Start a campaign",
  },

  campaignPage: {
    eyebrow: "Campaign #%n",
    left: "left",
    unreadable: "Could not be read",
    readingChain: "Reading from the chain…",
    back: "← all campaigns",
    joinEyebrow: "Join",
    joinTitle: "One transfer is enough.",
    amountLabel: "How much you will send (TRY)",
    amountAria: "How much you will send, in lira",
    preparing: "Preparing…",
    showIban: "Show the IBAN",
    joinNote:
      "If the goal is missed, all of this comes back to you, along with your share of the bonus.",
    notLiveYet:
      "The organizer has not locked the bonus yet (%f / %b USDC). The campaign opens for pledges once they do.",
    transferEyebrow: "Send your transfer",
    transferTitle: "Send it with these details.",
    recipient: "Recipient",
    amount: "Amount",
    willCredit: "Credited to the campaign",
    waiting: "Waiting…",
    confirmTransfer: "I sent the transfer (demo)",
    transferNote:
      "There is no real bank on the test network; this button reports that the transfer arrived. On the real network your bank does this step.",
    joined: "Your pledge is on the chain. You can find yourself in the counter.",
    failedEyebrow: "The goal was missed",
    failedTitle: "Your money is coming back.",
    yourReturn: "USDC — your pledge + your bonus share",
    sending: "Sending…",
    cashOut: "Send it to my IBAN",
    paidOut: "%a TRY was sent to your IBAN.",
    paidOutPlain: "Your money was sent to your IBAN.",
    succeeded: "The goal was met — it is happening. What was raised went to the organizer.",
    toGoal: "Toward the goal",
    peopleShort: "people",
    remaining: "to go",
    yourShare: "Your share",
    pledged: "You pledged",
    ifItFails: "If it misses, you get",
    rules: "Rules",
    lockedBonus: "Locked bonus",
    perPersonCap: "Cap per person",
    organizer: "Organizer",
  },

  newPage: {
    eyebrow: "New campaign",
    title: "Set the goal, lock the bonus.",
    note: "A campaign does not open for pledges until the bonus is in the contract. If the goal is missed it goes to the backers; if it is met it comes back to you. Not a promise — a rule enforced on Stellar.",
    whatFor: "What it is for",
    titlePlaceholder: "Late-night pizza",
    titleAria: "The campaign's name",
    goal: "Goal (USDC)",
    goalAria: "Goal, in USDC",
    bonus: "Bonus to lock (USDC)",
    bonusAria: "Bonus, in USDC",
    cap: "Cap per person (USDC)",
    capAria: "Bonus cap per person, in USDC",
    capNote: "A bonus share counts up to this amount per person.",
    duration: "Duration",
    durations: [
      { label: "5 min", seconds: 300 },
      { label: "1 hour", seconds: 3600 },
      { label: "1 day", seconds: 86_400 },
      { label: "1 week", seconds: 604_800 },
    ],
    opening: "Opening…",
    submit: "Open the campaign and lock the bonus",
    whyBonus: "Why there is a bonus",
    whyBonusText:
      "In “if enough people join” situations, everyone waits for somebody else to go first. The bonus tells whoever joins early “if it misses, you win” — which makes waiting pointless.",
    whyCap: "Why there is a cap",
    whyCapText:
      "A bonus share counts up to this amount per person. Dropping a large amount in at the last minute will not sweep the bonus.",
  },
};
