import type { Copy } from "./index";

export const tr: Copy = {
  meta: {
    title: "Stello — hedef tutmazsa, kazanan sen olursun",
    description:
      "Banka havalesiyle katıl. Hedef tutmazsa paran ve bonustan payın kendiliğinden hesabına döner.",
  },

  format: {
    locale: "tr-TR",
    over: "süre doldu",
    day: "gün",
    hour: "sa",
    minute: "dk",
    second: "sn",
  },

  verdict: { succeeded: "Tuttu", failed: "Tutmadı", waiting: "Bekliyor", open: "Açık" },

  steps: {
    account: "Hesabın açılıyor",
    trustline: "Para alabilmen için izin veriliyor",
    signin: "Ödeme kuruluşuna giriş yapılıyor",
    customer: "Kimliğin kaydediliyor",
    ticket: "Sana özel açıklama kodu alınıyor",
    deposit: "IBAN hazırlanıyor",
    "waiting-transfer": "Havalen bekleniyor",
    "waiting-chain": "Katılımın zincire yazılıyor",
    settled: "Kampanya sonuçlandırılıyor",
    claimed: "Paran hesabına aktarılıyor",
    withdrawing: "TL olarak IBAN'ına gönderiliyor",
    "paid-out": "Tamamlandı",
  },

  nav: {
    proof: "Kanıt",
    how: "Nasıl çalışır",
    guarantees: "Güvenceler",
    privacy: "Kriptosuz",
    toLight: "Açık temaya geç",
    toDark: "Koyu temaya geç",
    light: "Açık",
    dark: "Koyu",
    campaigns: "Kampanyalar",
    langLabel: "Switch to English",
  },

  hero: {
    headline: "Hedef tutmazsa, kazanan sen olursun.",
    mark: "kazanan sen",
    lede: "Banka uygulamandan TL gönder, katıl — cüzdan yok, kripto yok. Tutarsa iş olur; tutmazsa paran ve organizatörün baştan kilitlediği bonustan payın kendiliğinden geri döner.",
    join: "Bir kampanyaya katıl",
    joinHint: "IBAN'a havale yeter",
    create: "Kampanya aç",
    createHint: "bonusu sen kilitlersin",
    back: "Kampanyalarına dön",
    backHint: "bu tarayıcı seni hatırlıyor",
    countCampaigns: "kampanya açıldı",
    countPledged: "USDC taahhüt edildi",
    countPeople: "kişi katıldı",
    award: "Stellar testnet · zincirden canlı",
  },

  proof: {
    title: "Hedef tutmadı. Para kendiliğinden geri döndü.",
    lede: "Söz değil — kayıt. Aşağıdaki tur test ağında gerçekten koştu; her adımı isteyen herkes zincirden kontrol edebilir.",
    pledgedLabel: "Taahhüt edildi",
    pledgedOf: "/ 100 hedef",
    pledgedNote: "süre doldu, hedef tutmadı",
    lateLabel: "Süre dolduktan sonra gelen havale",
    lateValue: "İade",
    latePill: "3 birim · aynı işlemde geri gitti",
    returnedLabel: "Katılımcıya dönen",
    returnedValue: "5 / 5 — tamamı",
    returnedNote: "imzasına gerek kalmadan",
    jailTitle: "Katılımcı hiçbir şey yapmadı. Parası yine de döndü.",
    jailLede: "Varsayım değil — test ağında, gerçek bir kampanyada koştu. An be an:",
    jailSteps: [
      "Süre doldu, hedef tutmadı. Katılımcı *uygulamayı açmadı bile.*",
      "İadeyi bambaşka bir hesap tetikledi — kontrat kimin tetiklediğine bakmıyor.",
      "Para çağırana değil, katılımcının kendi hesabına gitti. **Kuruşu kuruşuna.**",
    ],
    jailFoot: "Tek işlem, birkaç saniye — Eylül 2026, Stellar testnet.",
    linkRefund: "İadeyi explorer'da gör ↗",
    linkRouter: "Yönlendirici kontrat ↗",
  },

  how: {
    title: "Nasıl çalışır",
    lede: "Senin yaptığın tek şey bir havale. Gerisini kontrat takip eder.",
    steps: [
      {
        n: "01",
        t: "Havaleni gönder",
        d: "Kampanyanın IBAN'ına, sana özel açıklama koduyla. Kurulacak cüzdan yok, saklanacak kelime yok, önce alınacak kripto yok.",
      },
      {
        n: "02",
        t: "Zincirde yerini al",
        d: "Para ulaştığı anda katılımın kontrata yazılır. Sayaç herkesin önünde akar; kimse listeyi elle tutmaz.",
      },
      {
        n: "03",
        t: "Ya olur ya kazanırsın",
        d: "Hedef tutarsa iş olur. Tutmazsa paran ve bonustan payın hesabına döner — sen bir şey yapmadan.",
      },
    ],
    link: "Nasıl kuruldu →",
  },

  guarantees: {
    title: "Kontratın zorla uyguladığı dört şey",
    lede: "Bir uygulamadaki ayarlar değil, birinin “merak etme” demesi hiç değil. Para hareket etmeden önce kontratın baktığı kurallar.",
    items: [
      {
        n: "01",
        t: "Bonus baştan kilitli",
        d: "Organizatör bonusu kontrata yatırmadan kampanya katılıma açılmaz. Söz laf olarak değil, para olarak durur.",
      },
      {
        n: "02",
        t: "Kişi başı tavan",
        d: "Bonus payı kişi başı bir tavana kadar sayılır. Son dakikada büyük para koyup bonusu toplamak işe yaramaz.",
      },
      {
        n: "03",
        t: "İade imza istemez",
        d: "Parayı geri göndermeyi herkes tetikleyebilir ama para yalnız sahibine gider. Telefonunu kaybeden de parasını alır.",
      },
      {
        n: "04",
        t: "Aynı havale iki kez sayılmaz",
        d: "Her ödemenin zincirde tek bir kimliği var. Aktarıcı iki kez çalışsa da kontrat ikincisini reddeder.",
      },
    ],
    keyText: "“Yeterli kişi olursa” işlerinde herkes başkasının önce davranmasını bekler. ",
    keyStrong: "Burada beklemenin ödülü yok, katılmanın var.",
    link: "Kontrat mekaniği →",
  },

  privacy: {
    title: "Zincirin güvencesini al — zinciri öğrenmeden.",
    lede: "Katılmak için bildiğin tek şeyi yapıyorsun: havale. Cüzdan kurmak, kelime saklamak, borsadan kripto almak yok. Yine de paranın kuralı bir şirketin sözü değil, herkesin okuyabildiği bir kontrat.",
    cards: [
      { k: "Cüzdan", v: "•••••", note: "gerekmiyor" },
      { k: "Kripto satın almak", v: "•••••", note: "gerekmiyor" },
      { k: "Katılımın", v: "Kayıtlı", note: "zincirde, herkese açık" },
    ],
    link: "Havale nasıl kontrat çağrısına dönüşüyor →",
  },

  finalCta: {
    title: "Bir havale uzağındasın.",
    lede: "Kurulacak cüzdan yok, saklanacak kelime yok, önce alınacak kripto yok. Bir kampanya seç, IBAN'a gönder; gerisini kontrat takip eder.",
    browse: "Kampanyalara bak",
    create: "Kampanya aç →",
  },

  footer: {
    line: "Banka havalesi, kontrat çağrısı olur — kuralların bir sözde değil, kontratta durur.",
    product: "Ürün",
    campaigns: "Kampanyalar",
    create: "Kampanya aç",
    resources: "Kaynaklar",
    architecture: "Mimari ve güven modeli ↗",
    onChain: "Zincirde",
    router: "Yönlendirici kontrat",
    campaignContract: "Kampanya kontratı",
    landing: "İniş hesabı",
    badge: "Stellar Testnet",
    openSource: "Açık kaynak, her satırı okunabilir.",
    totals: "%c kampanya · %a USDC taahhüt — hepsi yukarıdan kontrol edilebilir.",
    author: "Seyit Ali Değirmen tarafından yapıldı",
    event: "Stellar Pro Hackathon · İstanbul, Eylül 2026",
  },

  shell: {
    campaigns: "Kampanyalar",
    create: "Kampanya aç",
    testnet: "⚠ Test ağı — test parası, gerçek para değil.",
    docs: "Nasıl çalışıyor ↗",
    close: "Kapat",
  },

  campaignsPage: {
    emptyTitle: "Yeterli kişi çıkarsa olacak işler için.",
    emptyNote:
      "Hedefi ve süreyi koy, bonusu kilitle. Katılanlar yalnızca havale gönderir; tutmazsa paraları ve bonus payları kendiliğinden döner.",
    emptyCta: "İlk kampanyayı aç",
    featuredEyebrow: "Şu an katılabileceğin",
    featuredLeft: "%t kaldı",
    peopleJoined: "kişi katıldı",
    openCampaign: "Kampanyayı aç →",
    reading: "Okunuyor…",
    noneYet: "Şimdilik yok",
    noneNote:
      "Açık bir kampanya olduğunda burada görünür — kalan süresi, toplanan tutarı ve katılan kişi sayısıyla.",
    allCampaigns: "Bütün kampanyalar",
    open: "açık",
    closed: "kapandı",
    colLeft: "Kalan",
    colStatus: "Durum",
    colCampaign: "Kampanya",
    colRaised: "Toplanan",
    readingChain: "Zincirden okunuyor…",
    noCampaigns: "Henüz kampanya yok.",
    howToJoin: "Nasıl katılırım",
    joinSteps: [
      "Bir kampanya seç, ne kadar TL göndereceğini yaz.",
      "Verilen IBAN'a, sana özel açıklama koduyla havale yap.",
      "Tutmazsa paran ve bonus payın kendiliğinden döner.",
    ],
    rules: "Kurallar",
    ruleBonus: "Bonus",
    ruleBonusValue: "baştan kilitli",
    ruleRefund: "İade",
    ruleRefundValue: "imza istemez",
    ruleOnce: "Aynı havale",
    ruleOnceValue: "bir kez sayılır",
    create: "Kampanya aç",
  },

  campaignPage: {
    eyebrow: "Kampanya #%n",
    left: "kaldı",
    unreadable: "Okunamadı",
    readingChain: "Zincirden okunuyor…",
    back: "← tüm kampanyalar",
    joinEyebrow: "Katıl",
    joinTitle: "Bir havale yeter.",
    amountLabel: "Göndereceğin tutar (TL)",
    amountAria: "Göndereceğin tutar, TL",
    preparing: "Hazırlanıyor…",
    showIban: "IBAN'ı göster",
    joinNote: "Hedef tutmazsa bu tutarın tamamı, bonustan payınla birlikte geri döner.",
    notLiveYet:
      "Organizatör bonusu henüz kilitlemedi (%f / %b USDC). Kampanya o zaman katılıma açılır.",
    transferEyebrow: "Havaleni gönder",
    transferTitle: "Bu bilgilerle gönder.",
    recipient: "Alıcı",
    amount: "Tutar",
    willCredit: "Kampanyaya yazılacak",
    waiting: "Bekleniyor…",
    confirmTransfer: "Havaleyi yaptım (demo)",
    transferNote:
      "Test ağında gerçek banka yok; bu düğme havalenin ulaştığını bildirir. Gerçek ağda bu adımı bankan yapar.",
    joined: "Katılımın zincire yazıldı. Sayaçta kendini görebilirsin.",
    failedEyebrow: "Hedef tutmadı",
    failedTitle: "Paran geri dönüyor.",
    yourReturn: "USDC — taahhüdün + bonus payın",
    sending: "Gönderiliyor…",
    cashOut: "IBAN'ıma çek",
    paidOut: "%a TL IBAN'ına gönderildi.",
    paidOutPlain: "Paran IBAN'ına gönderildi.",
    succeeded: "Hedef tuttu — iş oluyor. Toplanan tutar organizatöre geçti.",
    toGoal: "Hedefe kalan",
    peopleShort: "kişi",
    remaining: "kaldı",
    yourShare: "Senin payın",
    pledged: "Taahhüdün",
    ifItFails: "Tutmazsa alacağın",
    rules: "Kurallar",
    lockedBonus: "Kilitli bonus",
    perPersonCap: "Kişi başı tavan",
    organizer: "Organizatör",
  },

  newPage: {
    eyebrow: "Yeni kampanya",
    title: "Hedefi koy, bonusu kilitle.",
    note: "Bonus kontrata yatmadan kampanya katılıma açılmaz. Hedef tutmazsa katılanlara dağılır, tutarsa sana geri döner. Bir söz değil — Stellar'da zorlanan bir kural.",
    whatFor: "Ne için toplanıyor",
    titlePlaceholder: "Gece pizzası",
    titleAria: "Kampanyanın adı",
    goal: "Hedef (USDC)",
    goalAria: "Hedef, USDC",
    bonus: "Kilitlenecek bonus (USDC)",
    bonusAria: "Bonus, USDC",
    cap: "Kişi başı tavan (USDC)",
    capAria: "Kişi başı bonus tavanı, USDC",
    capNote: "Bonus payı kişi başı bu tutara kadar sayılır.",
    duration: "Süre",
    durations: [
      { label: "5 dk", seconds: 300 },
      { label: "1 saat", seconds: 3600 },
      { label: "1 gün", seconds: 86_400 },
      { label: "1 hafta", seconds: 604_800 },
    ],
    opening: "Açılıyor…",
    submit: "Kampanyayı aç ve bonusu kilitle",
    whyBonus: "Bonus neden var",
    whyBonusText:
      "“Yeterli kişi olursa” işlerinde herkes başkasının önce davranmasını bekler. Bonus, erken katılana “tutmazsa kazanırsın” der — beklemeyi anlamsız kılar.",
    whyCap: "Tavan neden var",
    whyCapText:
      "Bonus payı kişi başı bu tutara kadar sayılır. Son dakikada büyük para koyup bonusu toplamak işe yaramaz.",
  },
};
